name: AzureResources-CI-CD-zfAutomation

trigger:
- master

variables:
  azureSubscription: 'Microsoft Azure Internal Consumption (86a210e0-3877-4587-8ac4-9b5fa848fb0e)'
  functionAppName: 'mypocfunction'
  vmImageName: 'ubuntu-latest'
  workingDirectory: '$(System.DefaultWorkingDirectory)/'
  resourceGroupName: 'rainerdtl-TempStage-156316'
  keyVaultName: devopsmgmt-kv

stages:
- stage: Deploy
  displayName: Deploy Infrastructure

  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: 'development'
    pool:
      vmImage: $(vmImageName)

    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: '$(azureSubscription)'
              action: 'Create Or Update Resource Group'
              resourceGroupName: '$(resourceGroupName)'
              location: 'West Europe'
              templateLocation: 'Linked artifact'
              csmFile: '$(Pipeline.Workspace)/Deploy/ArmTemplates/appInsights.template.json'
              deploymentMode: 'Incremental'
              deploymentOutputs: 'appInsightsName'

          - bash: |
              echo "Created $(appInsightsName)"
            

