# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Microsoft Azure Internal Consumption(86a210e0-3877-4587-8ac4-9b5fa848fb0e)'
    subscriptionId: '86a210e0-3877-4587-8ac4-9b5fa848fb0e'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'rainerdtl-TempStage-156316'
    location: 'West Europe'
    templateLocation: 'Linked artifact'
    csmFile: '/Deploy/ArmTemplates/appInsights.template.json'
    deploymentMode: 'Incremental'
    deploymentOutputs: 'appInsightsName'
