parameters:
  serviceConnection: ""
  subscriptionId: ""
  resourceGroup: ""
  location: ""
  mode: ""
  armtemplate: ""
  storageaccountname: ""
  devopsorga: ""
  creationproject: ""
  creationteam: ""
  resourcePrefix: ""

steps:
  - task: AzureResourceManagerTemplateDeployment@3
    displayName: "Deploy: Azure LogicApp"
    inputs:
      deploymentScope: Resource Group
      azureResourceManagerConnection: ${{ parameters.serviceConnection }}
      subscriptionId: ${{ parameters.subscriptionId }}
      action: Create Or Update Resource Group
      resourceGroupName: ${{ parameters.resourceGroup }}
      location: ${{ parameters.location }}
      templateLocation: Linked artifact
      csmFile: ${{ parameters.armtemplate }}
      deploymentMode: ${{ parameters.mode }}
      overrideParameters: -AzDevOpsOrga "${{ parameters.devopsorga }}" -AzDevOpsCreationProject "${{ parameters.creationproject }}" -AzDevOpsCreationProjectTeam "${{ parameters.creationteam }}" -StorageAccounts_name "${{ parameters.storageaccountname }}" -ResourcePrefix "${{ Parameters.resourcePrefix }}"