parameters:
  serviceConnection: ""
  subscriptionId: ""
  resourceGroup: ""
  location: ""
  mode: ""
  name: ""
  armtemplate: ""

steps:
  - task: AzureResourceManagerTemplateDeployment@3
    displayName: "Deploy: Azure Storage"
    inputs:
      deploymentScope: "Resource Group"
      azureResourceManagerConnection: ${{ parameters.serviceConnection }}
      subscriptionId: ${{ parameters.subscriptionId }}
      action: "Create Or Update Resource Group"
      resourceGroupName: ${{ parameters.resourceGroup }}
      location: "${{ parameters.location }}"
      templateLocation: "Linked artifact"
      csmFile: "${{ parameters.armtemplate }}"
      deploymentMode: ${{ parameters.mode }}
      overrideParameters: '-storageAccounts_name "${{ parameters.name }}"'