parameters:
  serviceConnection: ""
  subscriptionId: ""
  resourceGroup: ""
  location: ""
  mode: ""
  name: ""
  armtemplate: ""
  appmanagedIdentity: ""

steps:
  - bash: |
      echo "hello from keyvault yaml"

  - task: AzureResourceManagerTemplateDeployment@3
    displayName: "Deploy: Azure KeyVault"
    inputs:
      deploymentScope: Resource Group
      azureResourceManagerConnection: ${{ parameters.serviceConnection }}
      subscriptionId: ${{ parameters.subscriptionId }}
      action: Create Or Update Resource Group
      resourceGroupName: ${{ parameters.resourceGroup }}
      location: ${{ parameters.location }}
      templateLocation: Linked artifact
      csmFile: ${{ parameters.armtemplate }}
      deploymentMode: ${{ parameters.mode }}
      overrideParameters: -keyVaultName "${{ parameters.name }}" -enabledForTemplateDeployment true -location "$(location)"